services:
  gym.api:
    container_name: gym-api
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      gym.db:
        condition: service_healthy
      seq:
        condition: service_started
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:80
      ConnectionStrings__DefaultConnection: Server=gym.db,1433;Database=GymDB;User Id=sa;Password=Your_password123!;TrustServerCertificate=True;MultipleActiveResultSets=true;
      Serilog__WriteTo__1__Args__serverUrl: http://seq:5341
      JwtSettings__Issuer: gym-api
      JwtSettings__Audience: gym-api
      Email__ApiKey: ${EMAIL_API_KEY}
      Email__FromEmail: ${EMAIL_FROM_EMAIL}
      JwtSettings__Secret: ${JWT_SECRET}
      Stripe__SecretKey: ${STRIPE_SECRET_KEY}
      Stripe__PublishableKey: ${STRIPE_PUBLISHABLE_KEY}
      Stripe__WebhookSecret: ${STRIPE_WEBHOOK_SECRET}
    ports:
      - "8080:80"
    volumes:
      - uploads-data:/app/Uploads
    restart: unless-stopped
    networks:
      - gym-network

  gym.db:
    container_name: gym-db
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_PID: Developer
      MSSQL_SA_PASSWORD: Your_password123!
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql
    healthcheck:
      test:
        [
          "CMD-SHELL",
          '/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P "$${MSSQL_SA_PASSWORD}" -Q "SELECT 1" -C || exit 1',
        ]
      interval: 10s
      timeout: 15s
      retries: 10
      start_period: 40s
    restart: unless-stopped
    networks:
      - gym-network

  seq:
    container_name: gym-seq
    image: datalust/seq:latest
    environment:
      ACCEPT_EULA: "Y"
      SEQ_FIRSTRUN_ADMINPASSWORD: YourStrongPassword123!
    ports:
      - "5341:5341"
      - "8081:80"
    volumes:
      - seq-data:/data
    restart: unless-stopped
    networks:
      - gym-network

volumes:
  sqlserver-data:
  seq-data:
  uploads-data:

networks:
  gym-network:
    driver: bridge
