<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NSubstitute" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Gym.Domain\Gym.Domain.csproj" />
    <ProjectReference Include="..\..\src\Gym.Application\Gym.Application.csproj" />
    <ProjectReference Include="..\..\src\Gym.Infrastructure\Gym.Infrastructure.csproj" />
  </ItemGroup>
</Project>
