<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <Compile Remove="Common\NewFolder1\**" />
    <EmbeddedResource Remove="Common\NewFolder1\**" />
    <None Remove="Common\NewFolder1\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="MediatR" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Gym.Domain\Gym.Domain.csproj" />
  </ItemGroup>
</Project>
