name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "10.0.x"

      - name: Restore dependencies
        run: dotnet restore

      - name: Build solution
        run: dotnet build --configuration Release --no-restore

      - name: Run Unit Tests
        run: dotnet test tests/Gym.Domain.UnitTests/Gym.Domain.UnitTests.csproj --configuration Release --no-build

      - name: Run Application Tests
        run: dotnet test tests/Gym.Application.UnitTests/Gym.Application.UnitTests.csproj --configuration Release --no-build

      - name: Run Subcutaneous Tests
        run: dotnet test tests/Gym.Application.SubcutaneousTests/Gym.Application.SubcutaneousTests.csproj --configuration Release --no-build

      - name: Run Integration Tests
        run: dotnet test tests/Gym.Api.IntegrationTests/Gym.Api.IntegrationTests.csproj --configuration Release --no-build
